apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "configure k8s HPA with CPU metrics for Deployment"
  name: cpuscaler
  namespace: {{.Values.systemDefinitionNamespace}}
spec:
  appliesToWorkloads:
    - webservice
    - worker
  schematic:
    cue:
      template: |
