name: check-docs
on:
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - master
      - release-*
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Clean md files
        run: python ./hack/website/format.py markdown ./docs/en
      - name: Test Build
        env:
          VERSION: ${{ github.ref }}
        run: |
          bash ./hack/website/test-build.sh