name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  publish-cli:
    runs-on: ubuntu-latest
    env:
      VELA_VERSION: ${{ github.ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Clean md files
        run: python ./hack/website/format.py markdown ./docs/en
      - name: Sync release to kubevela.io Repo
        run: |
          bash ./hack/website/release.sh
      - name: Update kubectl plugin version in krew-index
        uses: rajatjindal/krew-release-bot@v0.0.38
