name: sync-core-api
on:
  push:
    tags:
      - "v*"
    branches:
      - master
      - release-*

jobs:
  sync-core-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        env:
          GO_VERSION: '1.14'
          GOLANGCI_VERSION: 'v1.38'
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Sync to kubevela-core-api Repo
        env:
          VELA_API_DEPLOY: ${{ secrets.VELA_API_DEPLOY }}
          VERSION: ${{ github.ref }}
          COMMIT_ID: ${{ github.sha }}
        run: |
          bash ./hack/apis/sync.sh


