name: sync-core-api
on:
  push:
    paths:
      - 'apis/**'
      - 'pkg/oam/**'
    branches:
      - master
      - release-*
env:
  # Common versions
  GO_VERSION: '1.14'
  GOLANGCI_VERSION: 'v1.38'
  VELA_API_DEPLOY: ${{ secrets.VELA_API_DEPLOY }}
  VERSION: ${{ github.ref }}
  COMMIT_ID: ${{ github.sha }}

jobs:
  sync-core-api:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Sync to kubevela-core-api Repo
        run: |
          bash ./hack/apis/sync.sh


